# -*- coding: utf-8 -*-

INGRESS_AGENT_DATA_FIELD_MAP = {
    "Time Span":                            r"ALL TIME",
    "Agent Name":                           r"\w+",
    "Agent Faction":                        r"Resistance|Enlightened",
    "Date (yyyy-mm-dd)":                    r"\d{4}-\d{2}-\d{2}",
    "Time (hh:mm:ss)":                      r"\d{2}:\d{2}:\d{2}",
    "Level":                                r"\d+",
    "Lifetime AP":                          r"\d+",
    "Current AP":                           r"\d+",
    "Unique Portals Visited":               r"\d+",
    "Unique Portals Drone Visited":         r"\d+",
    "Furthest Drone Distance":              r"\d+",
    "Portals Discovered":                   r"\d+",
    "Seer Points":                          r"\d+",
    "XM Collected":                         r"\d+",
    "OPR Agreements":                       r"\d+",
    "Portal Scans Uploaded":                r"\d+",
    "Uniques Scout Controlled":             r"\d+",
    "Resonators Deployed":                  r"\d+",
    "Links Created":                        r"\d+",
    "Control Fields Created":               r"\d+",
    "Mind Units Captured":                  r"\d+",
    "Longest Link Ever Created":            r"\d+",
    "Largest Control Field":                r"\d+",
    "XM Recharged":                         r"\d+",
    "Portals Captured":                     r"\d+",
    "Unique Portals Captured":              r"\d+",
    "Mods Deployed":                        r"\d+",
    "Hacks":                                r"\d+",
    "Drone Hacks":                          r"\d+",
    "Glyph Hack Points":                    r"\d+",
    "Overclock Hack Points":                r"\d+",
    "Completed treaks":                     r"\d+",
    "Completed Hackstreaks":                r"\d+",
    "Longest Sojourner Streak":             r"\d+",
    "Resonators Destroyed":                 r"\d+",
    "Portals Neutralized":                  r"\d+",
    "Enemy Links Destroyed":                r"\d+",
    "Enemy Fields Destroyed":               r"\d+",
    "Battle Beacon Combatant":              r"\d+",
    "Drones Returned":                      r"\d+",
    "Machina Links Destroyed":              r"\d+",
    "Machina Resonators Destroyed":         r"\d+",
    "Machina Portals Neutralized":          r"\d+",
    "Machina Portals Reclaimed":            r"\d+",
    "Max Time Portal Held":                 r"\d+",
    "Max Time Link Maintained":             r"\d+",
    "Max Link Length x Days":               r"\d+",
    "Max Time Field Held":                  r"\d+",
    "Largest Field MUs x Days":             r"\d+",
    "Forced Drone Recalls":                 r"\d+",
    "Distance Walked":                      r"\d+",
    "Kinetic Capsules Completed":           r"\d+",
    "Unique Missions Completed":            r"\d+",
    "Research Bounties Completed":          r"\d+",
    "Research Days Completed":              r"\d+",
    "Mission Day(s) Attended":              r"\d+",
    "NL-1331 Meetup(s) Attended":           r"\d+",
    "First Saturday Events":                r"\d+",
    "Second Sunday Events":                 r"\d+",
    "Clear Fields Events":                  r"\d+",
    "Prime Challenges":                     r"\d+",
    "OPR Live Events":                      r"\d+",
    "Operation Chronos Points":             r"\d+",
    "Cryptic Memories Global Op Points":    r"\d+",
    "Stealth Ops Missions":                 r"\d+",
    "Urban Ops Missions":                   r"\d+",
    "Agents Recruited":                     r"\d+",
    "Recursions":                           r"\d+",
    "Months Subscribed":                    r"\d+",
}
